### ISSUE TITLE
GraphicDecorationStackPane artifact

### ISSUE THREAD

**Issue by 5force** [effad/ValidatorFX#11]
GraphicDecorationStackPane  must be transparent because of artifact uprising when PopOver control use. 
```
public GraphicDecorationStackPane() {
		super();
		setId("graphic validator overlay stack");
                setStyle("-fx-background-color: rgba(0, 0, 0, 0);");
	}
```

**Comment by effad** [comment]
Can you elaborate please? What exactly is not working correctly? Maybe you can upload a screenshot showing the problem.

**Comment by 5force** [comment]
Yes, sure.
```
implementation 'net.synedra:validatorfx:0.1.11'
implementation 'org.controlsfx:controlsfx:11.0.2'
```
![popover](https://user-images.githubusercontent.com/29532204/95189881-11b50e80-0801-11eb-859c-66a04d886aa3.jpg)

**Comment by effad** [comment]
Ah I see. Is that screenshot from a demo application you could share?

**Comment by 5force** [comment]
I don't have a ready-made demo for this case, sorry. This was accidentally discovered when I was looking for a suitable validation javafx library. ControlsFX native validation support freezes GUI for a minute or so on PopOver.show() method. Unlike yours, thank you!

**Comment by effad** [comment]
I've just checked out controlsfx and I am getting the visual artifact in the FXSampler application itself (i.e. without ValidatorFX).

**Comment by effad** [comment]
> I've just checked out controlsfx and I am getting the visual artifact in the FXSampler application itself (i.e. without ValidatorFX).
Hmm. Under Windows the FXSampler demo works correctly. Under Linux it doesn't. Is your screenshot from Windows or Linux?

**Comment by effad** [comment]
Checking even further I found out that the PopOver works when using Gnome (Fedora 31) but not with fluxbox (which is my preferred window manager). Maybe this is some problem with the compositor?

**Comment by 5force** [comment]
I found it under Win7

**Comment by effad** [comment]
Can you run the FXSampler application on that machine and see if the PopOver demo there has the problem as well?
Or put the other way round: Have you checked that the fix you proposed really improves the situation for you?

**Comment by 5force** [comment]
In my case, this code fixed the buggy appearance, so I wrote about it

**Comment by effad** [comment]
While I am not convinced that we're addressing the root cause of the problem, there shouldn't be any negative side effects to making the GraphicDecorationStackPane transparent so I have integrated the proposed line of code.
ValidatorFX-0.1.12 (just released) will contain this fix.
