### ISSUE TITLE
How to combine 2 validations?

### ISSUE THREAD

**Issue by georgemoralis** [effad/ValidatorFX#14]
Supposely i have to check if a textfield  is empty and if it contains only letters, how can i combine that ?

in controlsfx i was using   Validators.combine

**Comment by effad** [comment]
Depending on the exact requirements you can either:
* create one check that checks both conditions
* create two checks that independently check each condition

e.g.: like this:
`
		validator.createCheck()
			.withMethod(c -> {
				String userName = c.get("username");
				if (userName.isBlank()) {
					c.error("Username is required.");
				} else if (!userName.toLowerCase().equals(userName)) {
					c.error("Please use only lowercase letters.");
				}
			})
			.dependsOn("username", userTextField.textProperty())
			.decorates(userTextField)
			.immediate();
		;

`
This will give the user **one specific** error message. Either it tells him that the username is required OR that it should consist of only lowercase letters. Since it is impossible for a blank username to contain letters that aren't lowercase, one could also write two separate checks:
`
		validator.createCheck()
			.withMethod(c -> {
				String userName = c.get("username");
				if (!userName.toLowerCase().equals(userName)) {
					c.error("Please use only lowercase letters.");
				}
			})
			.dependsOn("username", userTextField.textProperty())
			.decorates(userTextField)
			.immediate();
		;

		validator.createCheck()
			.withMethod(c -> {
				String userName = c.get("username");
				if (userName.isBlank()) {
					c.error("Username is required.");
				} 
			})
			.dependsOn("username", userTextField.textProperty())
			.decorates(userTextField)
			.immediate();
		;
`

**Comment by georgemoralis** [comment]
thanks! i had already found and used the first method

btw, your build doens't work with latest openjfx . (My project uses javafx 16 ) . When i add your lib from maven every window that has validation don't display any jfx controls. Updating your lib to match my javafx version solved the problem though

**Comment by georgemoralis** [comment]
my build for reference https://github.com/codebbgr/codebb-lib

**Comment by effad** [comment]
> thanks! i had already found and used the first method
> 
> btw, your build doens't work with latest openjfx . (My project uses javafx 16 ) . When i add your lib from maven every window that has validation don't display any jfx controls. Updating your lib to match my javafx version solved the problem though
That is interesting. Could you open another issue for that problem please and describe in detail what you did to make it work?

I'm also using ValidatorFX together with javafx.runtime.version=16+8 and had no such problems, maybe it has something to do with the platform and/or Java Version used?

**Comment by georgemoralis** [comment]
dunno if it is some other conflict , but once i compiled validatorfx with the same version as my app , all worked fine.

**Comment by effad** [comment]
Version 0.1.14 no longer contains any dependencies to JavaFX in the .pom-File to avoid problems with platform-specific .jar - Files.
0.1.14 also improves the display of graphic decorations.
You may want to try with this new version and see if the problems are gone.
