### ISSUE TITLE
Blurry graphic decoration node

### ISSUE THREAD

**Issue by torakiki** [effad/ValidatorFX#17]
I'm using a custom decoration node that's a bit bigger then the default one and the image is blurry, see the top image (how it is) vs the bottom image (how it should be):
![immagine](https://user-images.githubusercontent.com/3884479/125950599-9a0df017-e962-473c-af9d-bd75de6b6b97.png)

Same thing is valid for the default image but it's smaller and it seems less obvious:
![immagine](https://user-images.githubusercontent.com/3884479/125950732-7b7e3b1a-e121-4a90-89dc-1a5a0928d12a.png)

**Comment by effad** [comment]
I just integrated your PR (sorry for the long delay). It makes the graphic decoration look much nicer.
Thank you.
