### ISSUE TITLE
Support for JavaFX 8

### ISSUE THREAD

**Issue by effad** [effad/ValidatorFX#2]
At the moment build.gradle only works with newer Java Versions, since the javafx plugin is contained therein. 
Somehow this must be made optional.
Releases should also be made compatible so that ideally one .jar - File works with Java 8 and Java 11+

**Comment by effad** [comment]
Turns out this is not as simple as removing the JavaFX Plugin from `build.gradle`, we also require another version of ControlsFX.

**Comment by effad** [comment]
> any news on this?
Not really. Since I don't need it myself and (until now) noone asked for it, I didn't look into it.
Would you need it for Java 8?

**Comment by jaksatomovic** [comment]
Yes, most of my applications needs to be compatible with Java 8. Before I did the validations "manually" by myself but this lib is so much better. Only thing that block me is this java 8 compatibility  :(

**Comment by effad** [comment]
Experiment to compile ValidatorFX with Java 8:
* from build.gradle:
    * remove org.openjfx.javafxplugin
    * remove org.javamodularity.moduleplugin
    * remove compileTestJava closure
    * remove test closure
    * remove javafx closure
    * remove source/targetCompatiblilty
* remove module-info.java

Then we can execute `gradlew jar` and get ValidatorFX-0.4.0.jar.

Compiling ValidatorFXDemo against this .jar - file:
```
javac -cp ValidatorFX-0.4.0.jar ValidatorFXDemo.java
```

Commenting out the `scene.getStylesheets().add(...)` line I was able to run the demo.

**Comment by effad** [comment]
So here are the problems:
* For Java >=11 we really want modularity, so we cannot simply remove module-info.java
* We would need different build.gradle Versions
* We would also need different published .jar - Versions 

I've also discovered a small visual glitch in den Demo-Application (the small red icon displayed on the user name is off a few pixels) that is present only when using Java 8.

Since I don't have the time & resources to maintain the project in that way, and Java 11 is the most used version ATM, I'll close this issue as WONT FIX.
