### ISSUE TITLE
Add to JFXCentral

### ISSUE THREAD

**Issue by dlemmermann** [effad/ValidatorFX#20]
Any chance you could find the time to add this project to JFXCentral? https://github.com/dlemmermann/jfxcentral-data

**Comment by dlemmermann** [comment]
BTW, I finally used it in my last project, the health module for the coaching software I mentioned on Twitter. Worked very well. Much more lightweight than the ControlsFX validation support. Good job!

**Comment by effad** [comment]
> Any chance you could find the time to add this project to JFXCentral? https://github.com/dlemmermann/jfxcentral-data
Good idea. Will try to do so ASAP.

> BTW, I finally used it in my last project, the health module for the coaching software I mentioned on Twitter. Worked very well. Much more lightweight than the ControlsFX validation support. Good job!
Thank you :-).

**Comment by effad** [comment]
ValidatorFX is now presented at https://www.jfx-central.com/libraries/validatorfx.
