### ISSUE TITLE
problem with checks that are without immediate()

### ISSUE THREAD

**Issue by MoetezWelhazi** [effad/ValidatorFX#22]
for the life of me I couldn't figure out how to get validation results on submit like the Readme claimed when immediate() is not called. Is there any sample or snippet of functional code that could show how this is implemented?

**Comment by effad** [comment]
https://github.com/effad/ValidatorFX/blob/master/src/test/java/net/synedra/validatorfx/demo/ValidateOnSubmit.java is a full example on how to work without immediate() validation.

**Comment by effad** [comment]
Basically you just call `validator.validate()` and see if it returns true. After having called `validator.validate()` fields with invalid values will be decorated.

**Comment by effad** [comment]
Closing issue. If you have any further questions, feel free to reopen it.
