### ISSUE TITLE
TooltipWrapper: access Tooltip property

### ISSUE THREAD

**Issue by AntoninHuaut** [effad/ValidatorFX#23]
Hi,
I use a TooltipWrapper on my button and I would like to change the delay before the tooltip is displayed.
The problem is that the Tooltip field "disabledTooltip" is private in TooltipWrapper.
I don't know if you make the choice to make the field private is intentional. If so, is it possible to add methods that configure the tooltip?

Thanks

**Comment by effad** [comment]
Thank you for the PR that you sent. I'll try to release a new version ASAP.

**Comment by effad** [comment]
I just released 0.3.1, which contains your PR fot this issue.
