### ISSUE TITLE
My screen layout is getting messed up

### ISSUE THREAD

**Issue by Marcelphilippeandrade** [effad/ValidatorFX#28]
Hello everyone, I'm using ValidatorFx to validate the fields on my screen, but after using the feature:

**TooltipWrapper<Button> signUpWrapper = new TooltipWrapper<>(btnCadastrarLote,
validator.containsErrorsProperty(),
Bindings.concat("Please watch for errors:\n", validator.createStringBinding()));**

according to the documentation, the register button on my screen is getting disorganized, it is going up a few pixels on the screen. Could you help me? To facilitate the sharing of my code I created a repository on GitHub the address is: **https://github.com/Marcelphilippeandrade/Supermercado-Marcel.git**

I would also put a piece of code here:

**screen code:**
`<?xml version="1.0" encoding="UTF-8"?>

<?import javafx.scene.*?>
<?import javafx.geometry.*?>
<?import javafx.scene.effect.*?>
<?import javafx.scene.text.*?>
<?import java.lang.*?>
<?import javafx.scene.control.*?>
<?import javafx.scene.layout.*?>

<FlowPane fx:id="flowPaneLoteItem" maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="600.0" prefWidth="1000.0" xmlns="http://javafx.com/javafx/8" xmlns:fx="http://javafx.com/fxml/1" fx:controller="br.com.supermercado.marcel.controller.LoteItemController">
	<children>
		<TabPane fx:id="tabPaneLoteItem" prefHeight="200.0" prefWidth="1000.0">
			<tabs>
				<Tab fx:id="tabLote" closable="false" text="Lote">
					<content>
						<AnchorPane fx:id="anchorPaneLote" minHeight="0.0" minWidth="0.0" prefHeight="161.0" prefWidth="560.0">
							<children>
								<TextField fx:id="textFildCodigoLote" layoutX="109.0" layoutY="25.0" prefHeight="31.0" prefWidth="305.0" />
								<Label fx:id="labelCodigoLote" layoutX="38.0" layoutY="30.0" text="Código:">
									<font>
										<Font name="Arial" size="18.0" />
									</font>
								</Label>
								<Button fx:id="btnCadastrarLote" layoutX="38.0" layoutY="101.0" mnemonicParsing="false" onAction="#cadastrar" prefHeight="31.0" prefWidth="107.0" text="Cadastrar">
									<font>
										<Font name="Arial" size="15.0" />
									</font>
								</Button>
								<Button fx:id="btnLimparLote" layoutX="180.0" layoutY="101.0" mnemonicParsing="false" onAction="#limpar" prefHeight="31.0" prefWidth="118.0" text="Limpar" />
                        		<Label fx:id="labelDataFabricacao" layoutX="473.0" layoutY="30.0" text="Data Fabricação:">
                           			<font>
                              			<Font name="Arial" size="18.0" />
                           			</font>
                        		</Label>
                        		<DatePicker fx:id="datePikerLote" layoutX="624.0" layoutY="25.0" prefHeight="31.0" prefWidth="235.0" />
							</children>
						</AnchorPane>
					</content>
				</Tab>
				<Tab fx:id="tabItem" closable="false" text="Item">
					<content>
						<AnchorPane minHeight="0.0" minWidth="0.0" prefHeight="161.0" prefWidth="577.0" />
					</content>
				</Tab>
			</tabs>
		</TabPane>
	</children>
</FlowPane>
`
**controller code:**
`package br.com.supermercado.marcel.controller;

import java.time.LocalDate;
import br.com.supermercado.marcel.interfaces.InterfaceCadastro;
import javafx.beans.binding.Bindings;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.fxml.FXML;
import javafx.scene.Node;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;
import javafx.scene.control.DatePicker;
import javafx.scene.control.Tab;
import javafx.scene.control.TabPane;
import javafx.scene.control.TextField;
import javafx.scene.control.Tooltip;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.FlowPane;
import net.synedra.validatorfx.TooltipWrapper;
import net.synedra.validatorfx.Validator;

public class LoteItemController implements InterfaceCadastro {

	@FXML
	private TextField textFildCodigoLote;

	@FXML
	private Button btnLimparLote;

	@FXML
	private Button btnCadastrarLote;

	@FXML
	private FlowPane flowPaneLoteItem;
	
	@FXML
	private AnchorPane anchorPaneLote;
	
	@FXML
	private DatePicker datePikerLote;

	private Validator validator;

	public LoteItemController() {
		this.validator = new Validator();
		this.btnLimparLote = new Button();
		this.btnCadastrarLote = new Button();
		this.textFildCodigoLote = new TextField();
		this.datePikerLote = new DatePicker();
	}

	public void limpar() {
		btnLimparLote.setOnAction(new EventHandler<ActionEvent>() {
			public void handle(ActionEvent event) {
				resetTextFildCodigoLote();
			}
		});
	}

	public void cadastrar() {
		
		validator.createCheck()
		.dependsOn("codigo", textFildCodigoLote.textProperty())
		.dependsOn("datePikerLote", datePikerLote.valueProperty()).withMethod(c -> {
			String codigo = c.get("codigo");
			LocalDate dataFabricacaoPikerLote = c.get("datePikerLote");
			if (codigo.isEmpty() && dataFabricacaoPikerLote == null) {
				c.error("O campo código do lote não pode ser vazio.");
				c.error("O campo data de fabricação não pode ser vazio.");
				TooltipWrapper<Button> signUpWrapper = new TooltipWrapper<>(btnCadastrarLote,
						validator.containsErrorsProperty(),
						Bindings.concat("Favor observar os erros:\n", validator.createStringBinding()));
				anchorPaneLote.getChildren().add(signUpWrapper);
			}
		}).decorates(textFildCodigoLote).decorates(datePikerLote).immediate();
		
		
		btnCadastrarLote.setOnAction(new EventHandler<ActionEvent>() {
			public void handle(ActionEvent event) {
			}
		});
	}

	private void resetTextFildCodigoLote() {
		textFildCodigoLote.setText("");
		datePikerLote.setValue(null);
	}

	private void alertaInformacao(String mensagem) {
		Alert alertSucesso = new Alert(AlertType.INFORMATION);
		alertSucesso.setTitle("Alerta");
		alertSucesso.setContentText(mensagem);
		alertSucesso.show();
	}

	private Tooltip tooltipErro(String mensagem) {
		Tooltip toolTip = new Tooltip();
		toolTip.setText(mensagem);
		toolTip.setStyle("-fx-background-color: red;");
		btnCadastrarLote.setTooltip(toolTip);
		return toolTip;
	}
}
`
**Main application code:**
`package br.com.supermercado.marcel.main;

import java.net.URL;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.FlowPane;
import javafx.stage.Stage;

public class Aplicacao extends Application {

	@Override
	public void start(Stage primaryStage) throws Exception {

		FlowPane flowPaneLoteItem = new FlowPane();
		URL fxmlUrlTelaLoteItem = this.getClass().getClassLoader().getResource("br/com/supermercado/marcel/telas/TelaLoteItem.fxml");
		flowPaneLoteItem = FXMLLoader.<FlowPane>load(fxmlUrlTelaLoteItem);

		Scene minhaCena = new Scene(flowPaneLoteItem);
		primaryStage.setScene(minhaCena);
		primaryStage.setResizable(false);
		primaryStage.show();
	}

	public static void main(String args[]) {
		launch(args);
	}
}
`

**Comment by effad** [comment]
Sorry for the late response. I've tried to reproduce your problem but so far I have failed to get your application running.
Which JDK are you using? How can your application be run from the command line?

**Comment by effad** [comment]
Without actually reproducing the problem I can see a problem in your code: You must not create the signupWrapper in the check method. It must be created once only, not everytime a check happens. It also has to be added to the scenegraph in order to work.
