### ISSUE TITLE
Turn a Check to immediate after first call to Validator.validate()

### ISSUE THREAD

**Issue by gldiazcardenas** [effad/ValidatorFX#33]
I see this convinient, specially to let the user know he has fixed the issue.   Or at least make it optional in case somebody wants this behavior.

**Comment by effad** [comment]
This would  (Like issue #32) make a "hybrid"-mode possible, where checks are not immediate from the start (and thus mark required fields as soon as a form is displayed) while allowing to give immediate feedback once the user has fixed a problem.

**Comment by effad** [comment]
Methods to change the mode of a single Check or all the Checks of a Validator have been added, together with a new "immediate clear" mode. This will be part of the upcoming 0.5.0 release.
