### ISSUE TITLE
Add a withMethods function to allow for more then one method to be used

### ISSUE THREAD

**Issue by colindj1120** [effad/ValidatorFX#36]
This would allow some duplicated code to be pulled out to different functions like this for a text field 

```java
    private static Consumer<Context> checkEmptyText(String fieldName) {
        return c ->
        {
            String text = c.get("text");
            if (text.trim()
                    .isEmpty()) {
                c.error(fieldName + " Cannot Be Empty");
            }
        };
    }
``` 

I would want to use this function in multiple text fields however some text fields also need to be checked for other properties as well

**Comment by effad** [comment]
.withMethod can now be called multiple times, Check will keep a list of check methods to execute. This will be part of the upcoming 0.5.0 release.
